### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by Fozzar** [JerimiahOfficial/StartupMillenium#2]
![Screenshot_5](https://user-images.githubusercontent.com/41928860/124963891-08273400-e029-11eb-9d6f-fb17c2bd51a8.png)
My Garrysmod directory: D:\Programs\Steam\steamapps\common\GarrysMod

**Comment by JerimiahOfficial** [comment]
This is cause the program is searching for `<drive>:\Program Files (x86)\Steam\steamapps\common\GarrysMod` instead of where your directory for garrysmod is. Usually, steam is installed in `Program Files (x86)` on your `C:\ drive`, therefore it was made to look in this certain directory.

A way you can fix this is to hard code your directory into the program, I will try to fix this issue in the future and if you'd like I can make a version for your specified directory.

**Comment by gage-lodba** [comment]
Fixed in latest release
